import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Fragment } from "react";
import menu from "../menu";
import styles from "../styles/Home.module.css";

export default function Home({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navBar}>
        <Link href="/">
          <img className={styles.image} src="/main.jpg" />
        </Link>
        <ul>
          {menu.map((el, index) => {
            if (el.children) {
              return (
                <Fragment key={index}>
                  <li>
                    <button>{el.title}</button>
                  </li>
                  <ul className={styles.works}>
                    {el.children.map((el, index) => (
                      <li key={index}>
                        <Link href={`/works/${el.slug}`}>{el.title}</Link>
                      </li>
                    ))}
                  </ul>
                </Fragment>
              );
            } else {
              return (
                <li key={index}>
                  <Link href={`/${el.slug}`}>{el.title}</Link>
                </li>
              );
            }
          })}
        </ul>
        <img className={styles.image} src="/second.jpg" />
      </nav>
      <main className={styles.main}>
        <div className={styles.mainContent}>{children}</div>
      </main>
    </div>
  );
}
